package com.ralitski.util.comm.packet;

/**
 * thrown by Packet.write(Packet p, DataOutputStream out) when an unregistered packet is passed.
 *
 * @author ralitski
 */
public class PacketTypeNotFoundException extends Exception {

    /**
	 * autogenerated id
	 */
	private static final long serialVersionUID = -1692779144178469041L;
	
	//the class of the unregistered packet
    private Class<? extends Packet> c;

    public PacketTypeNotFoundException(Class<? extends Packet> c) {
        this.c = c;
    }

    @Override
    public String toString() {
        return super.toString() + ":" + c.getName();
    }

}
